services:
  - type: web
    name: personal-diary-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: personal-diary-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://personal-diary-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://personal-diary-frontend.onrender.com
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True 